%%%
  VERSION:1
  LANGUAGE:ENGLISH
%%%
MODULE MOD_ABBTestProg1

    ! -------------------------------
    ! Define customized variables here
    ! ...

	! Tool variables: 

	! Reference variables:
	PERS wobjdata RobotBase := [FALSE, TRUE, "", [[0,0,0],[1,0,0,0]],[[0.000,0.000,0.000],[1.00000000,0.00000000,0.00000000,0.00000000]]];

	PROC Main()
		ConfJ \On;
		ConfL \Off;
		! Program generated by RoboDK v5.9.4 for ABB IRB 6700-245/3.00 SpotPack on 13/01/2026 12:25:36
		! Using nominal kinematics.
		MoveL [[2192.500,0.000,2125.000],[0.70710678,0.00000000,0.70710678,0.00000001],[0,0,-1,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,tool0 \WObj:=RobotBase;
		MoveL [[2192.500,657.053,2125.000],[0.70710678,0.00000000,0.70710678,0.00000001],[0,-1,0,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,tool0 \WObj:=RobotBase;
		MoveL [[2192.500,657.053,1505.390],[0.70710678,0.00000000,0.70710678,0.00000001],[0,-2,1,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,tool0 \WObj:=RobotBase;
		MoveL [[2192.500,-46.451,1505.390],[0.70710678,0.00000000,0.70710678,0.00000001],[-1,-3,2,0],[9E+09,9E+09,9E+09,9E+09,9E+09,9E+09]],v500,z1,tool0 \WObj:=RobotBase;
	ENDPROC

ENDMODULE
